---
- name: install neutron controller components
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - python-neutronclient

- name: Creates scripts
  file: path=~/scripts state=directory

- name: create neutron-entities
  template: src=scripts/neutron-init.sh.j2 dest=~/scripts/neutron-init.sh mode="u+x"
  register: neutron_entities

- name: execute neutron-entities
  shell: ~/scripts/neutron-init.sh
  when: neutron_entities.changed

- name: write the neutron patch tenantid file
  copy: src=neutron-set-tenantid.sh dest=~/scripts/neutron-set-tenantid.sh mode="u+x"

- name: write the neutron config file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf.templ
  sudo: true
  register: neutron_config
  notify:
    - restart neutron controller

- name: write the neutron ml2 file
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini
  sudo: true
  notify:
    - restart neutron controller

- name: set neutron tenantid
  sudo: true
  shell: scripts/neutron-set-tenantid.sh
  when: neutron_config.changed

- name: populate neutrondb
  sudo: true
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade juno" neutron
  when: neutron_config.changed

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/neutron/neutron.sqlite state=absent