- name: Provision Controller
  hosts: controller*
  roles:
    - openstack-db
    - rabbitmq
#    - keystone
#    - glance
#    - nova-controller
#    - neutron
#    - cinder-controller
#    - heat
#    - horizon